### ISSUE TITLE
Incorrect transformation for rastererized box

### ISSUE THREAD

**Issue by RArbore** [frozein/DoonEngine#7]
On my machine, the rasterized box looks like this:

![2022-07-04-185202_2256x1504_scrot](https://user-images.githubusercontent.com/51011371/177226732-b3609853-0d7f-44cd-9a01-9366c1e079c3.png)
![2022-07-04-185206_2256x1504_scrot](https://user-images.githubusercontent.com/51011371/177226734-6c7587c5-dcfc-48f0-a7af-911296c5fb40.png)
![2022-07-04-185218_2256x1504_scrot](https://user-images.githubusercontent.com/51011371/177226737-10ff9ba9-8d37-4720-8ee2-890d7cb618cc.png)
![2022-07-04-185159_2256x1504_scrot](https://user-images.githubusercontent.com/51011371/177226729-e7e30237-8afd-4b3d-9cff-c9df355f4888.png)

It does seem to play well with transparency, so it looks like the vertex shader for the raster stage is just getting bad input.

**Comment by frozein** [comment]
It definitely seems like a vertex transformation issue. I can't seem to reproduce this issue on either of my machines, so could you find out the source? It is likely the model or projection matrix.

**Comment by RArbore** [comment]
Sure, I'll find some time this week to investigate this further.

**Comment by RArbore** [comment]
Closing since this is fixed with #8

**Comment by dd123-a** [comment]
Does this scene require modifying the code by oneself to create it?
